name: CI/CD Pipeline - AWS ECS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1

    - name: Login to Amazon ECR
      id: ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build & push Backend image
      run: |
        docker build -t conduit-backend ./backend
        docker tag conduit-backend:latest ${{ steps.ecr.outputs.registry }}/conduit-backend:latest
        docker push ${{ steps.ecr.outputs.registry }}/conduit-backend:latest

    - name: Build & push Frontend image
      run: |
        docker build -t conduit-frontend ./frontend
        docker tag conduit-frontend:latest ${{ steps.ecr.outputs.registry }}/conduit-frontend:latest
        docker push ${{ steps.ecr.outputs.registry }}/conduit-frontend:latest

    - name: Update ECS service
      run: |
        aws ecs update-service \
          --cluster conduit-cluster \
          --service conduit-task-service-727a76rm \
          --force-new-deployment
          --region eu-north-1
